syntax = "proto3";

package relayx.order.v1;
import "common/common.proto";

service OrderService {
  rpc CreateOrder (CreateOrderRequest) returns (OrderResponse);
  rpc ListOrders (ListOrdersRequest) returns (ListOrdersResponse);
  rpc CheckHealth (relayx.common.v1.Empty) returns (HealthCheckResponse);
}

message CreateOrderRequest {
  string user_id = 1;
  repeated string item_ids = 2;
  double total_amount = 3;
}

message OrderResponse {
  string order_id = 1;
  string user_id = 2;
  string status = 3;
  double total_amount = 4;
}

message ListOrdersRequest {
  string user_id = 1;
  relayx.common.v1.PaginationRequest pagination = 2;
}

message ListOrdersResponse {
  repeated OrderResponse orders = 1;
  relayx.common.v1.PaginationResponse pagination = 2;
}

message HealthCheckResponse {
  relayx.common.v1.HealthStatus status = 1;
}